spring:
  application:
    name: NflpBackend
  datasource:
    url: jdbc:postgresql://localhost:5432/nflp
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

nlp:
  service:
    url: http://localhost:5002
